### ISSUE TITLE
Use the magic of nested scenes to standardize all the things

### ISSUE THREAD

**Issue by AevumDecessus** [fragforce/FFOverlays#2]
1) Create scene for camera 1, add webcam source to it
2) Create scene for camera 2, add camera source to it as well
3) Create scene for alerts
4) On main overlay scene, add scene (camera1) as a source, position it in the webcam location
5) Now add Alerts scene, etc

This lets you do fancy complicated things in a repeatable way that easily nest due to the way that OBS lets you use entire scenes as sources in other scenes :-D

**Comment by BenG-SFDC** [comment]
Bumped the webcam and frame into its own scene, added bot alerts to its own scene to allow nesting easily, and changing webcams should be much easier.
